// <auto-generated />
namespace inventory___sales_management_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class tableedits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tableedits));
        
        string IMigrationMetadata.Id
        {
            get { return "202506081752098_tableedits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
